name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    RUST_BACKTRACE: 1

jobs:
  style:
    name: verify formatting and style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ⚡ Cache
      uses: Swatinem/rust-cache@v1.3.0
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: 🔎 Verify code formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt 
        args: -- --check
    
    - name: 🔎 Verify code style
      uses: actions-rs/cargo@v1
      with:
        command: clippy 
        args: --all-targets --all-features -- -D warnings

  build:
    name: build and run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ⚡ Cache
      uses: Swatinem/rust-cache@v1.3.0
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: 🔨 Build
      uses: actions-rs/cargo@v1
      with:
        command: build 
        args: --verbose --all-features
    
    - name: 📖 Docs
      uses: actions-rs/cargo@v1
      with:
        command: rustdoc 
        args: --lib --all-features --examples
    
    - name: 🔎 Test
      uses: actions-rs/cargo@v1
      with:
        command: test 
        args: --verbose --all-features
    
    - name: 🔎 timezone-sensitive tests in non UTC (GMT-5)
      uses: actions-rs/cargo@v1
      env:
        TZ: std +5
      with:
        command: test 
        args: --verbose --all-features graph
